
FROM golang:1.23-alpine AS build
WORKDIR /helloworld
# Copy dependencies list
COPY go.mod go.sum ./
# Build with optional lambda.norpc tag
COPY main.go .
RUN go build -tags lambda.norpc -o main main.go

# Copy artifacts to a clean image
FROM alpine:3.16
COPY --from=build /helloworld/main ./main
ENTRYPOINT [ "./main" ]